export default [
    'tomatoes',
    'lime',
    'lettuce',
    'Green olives',
    'mayonnaise',
    // cheese
    'Feta',
    'medium cheddar',
    'sharp cheddar',
    'shredded Parmesan',
    'grated Parmesan',
    'cream cheese',
    'shredded mozzarella',
    // meet
    'beef',
    'beef steak',
    'ground beef',
    'eggs',
    'boneless chicken breasts',
    'sliced pepperoni',
    'bacon',
    'sliced Genoa salami',
    'pepperoni sticks',
    'beef hot dogs',
    'pork',
    'chicken',
    'chicken breast',
    // vegetables
    'Carrots',
    'Potato',
    'Tomato',
    'Onions',
    'Broccoli',
    'Mushroom',
    'Lettuce',
    'Capsicum',
    'Pumpkin',
    'Zucchini',
    //fruits
    'Strawberry',
    'Grape',
    'Watermelon',
    'Banana',
    'Orange',
    'Peach',
    'Mango',
    'Apple',
    'Pineapple',
    'Cherry',

].sort() // sorting alphabetical